server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:user_service_user}
    password: ${SPRING_DATASOURCE_PASSWORD:user_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info