server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: messaging-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/messaging_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:messaging_service_user}
    password: ${SPRING_DATASOURCE_PASSWORD:messaging_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always